In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv(r"A:\ML AI\UNZIP_FOR_NOTEBOOKS_FINAL\08-Linear-Regression-Models\Advertising.csv")

In [6]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [7]:
X=df.drop('sales',axis=1)
y=df['sales']

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [10]:
poly_features = polynomial_converter.fit_transform(X)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

# ----
----

## Scaling the Data

While our particular data set has all the values in the same order of magnitude ($1000s of dollars spent), typically that won't be the case on a dataset, and since the mathematics behind regularized models will sum coefficients together, its important to standardize the features. Review the theory videos for more info, as well as a discussion on why we only **fit** to the training data, and **transform** on both sets separately.

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
#help(StandardScaler)

In [15]:
scaler=StandardScaler()

In [16]:
scaler.fit(X_train)

StandardScaler()

In [17]:
X_train = scaler.transform(X_train)
X_test - scaler.transform(X_test)

array([[7.56133947e+01, 4.76374058e+01, 4.50183144e+01, ...,
        1.11522357e+05, 1.03170511e+05, 9.54438943e+04],
       [2.54168789e+02, 2.66634404e+01, 6.69601922e+00, ...,
        3.98048066e+03, 8.14329025e+02, 1.66920477e+02],
       [1.13360025e+02, 1.78077661e+01, 3.82499489e+01, ...,
        1.16869667e+04, 2.59255404e+04, 5.75126138e+04],
       ...,
       [4.08311597e+01, 3.99003430e+01, 6.98200649e+00, ...,
        9.79789648e+03, 1.38319970e+03, 1.95657283e+02],
       [2.64247732e+02, 2.02314244e+01, 1.73890640e+00, ...,
        1.20723313e+02, 2.41591305e+00, 5.73601928e-01],
       [1.74821815e+02, 2.25618650e+01, 3.14815833e+01, ...,
        1.59471979e+04, 2.23259141e+04, 3.12562103e+04]])

# Ridge Regression


In [18]:
from sklearn.linear_model import Ridge

In [19]:
ridge_model=Ridge(alpha=10)

In [20]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [21]:
test_predictions = ridge_model.predict(X_test)

In [22]:
test_predictions

array([-7.41563598e+04, -9.64309614e+06, -9.98161188e+05, -5.96261073e+05,
        9.71491110e+03, -1.06068803e+03, -1.07768579e+07, -5.73987184e+06,
       -1.79468032e+06, -6.61556631e+06,  4.14757019e+04, -3.17627116e+06,
       -7.11918169e+06, -4.65716332e+06, -5.05727332e+06, -1.98950912e+04,
       -1.19168528e+07, -5.73943300e+05, -7.84125345e+04, -7.00102481e+06,
        3.36399192e+03, -2.85979239e+06, -1.24621160e+07, -1.11521485e+07,
       -1.80491724e+05, -5.61173346e+06, -1.46480586e+07, -1.79227485e+05,
       -2.93454091e+06, -2.80861369e+04, -1.90560212e+04, -6.70528392e+06,
       -1.55235431e+06, -1.04418777e+04, -3.36741689e+06, -7.07319198e+05,
       -4.54171651e+05, -5.34482287e+05, -8.16948736e+03, -2.46987656e+06,
       -3.67534287e+05, -1.93249772e+06, -6.44504431e+05, -1.09647031e+04,
       -2.09769910e+05, -1.71250970e+05, -5.43681317e+02, -8.17133232e+06,
       -4.45611889e+06, -4.33704495e+06, -8.74456435e+02, -5.91721855e+06,
       -1.42073217e+07, -

In [23]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [24]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [25]:
MAE

3552540.8630772433

In [26]:
MSE

30185228810872.824

In [27]:
RMSE

5494108.554704105

# How did it perform on the training set? (This will be used later on for comparison)

In [28]:
# Training Set Performance
train_predictions = ridge_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.528834818302533

# Choosing an alpha value with Cross-Validation

In [29]:
from sklearn.linear_model import RidgeCV

In [30]:
# Choosing a scoring: https://scikit-learn.org/stable/modules/model_evaluation.html
# Negative RMSE so all metrics follow convention "Higher is better"

# See all options: sklearn.metrics.SCORERS.keys()
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')

In [31]:
# The more alpha options you pass, the longer this will take.
# Fortunately our data set is still pretty small
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [32]:
ridge_cv_model.alpha_

0.1

In [33]:
test_predictions = ridge_cv_model.predict(X_test)

In [34]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [35]:
MAE

14346988.002533497

In [36]:
MSE

497869449601560.94

In [37]:
RMSE

22312988.361077074

In [38]:
# Training Set Performance
# Training Set Performance
train_predictions = ridge_cv_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.30941321056368337

In [39]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

# -----

## Lasso Regression

In [40]:
from sklearn.linear_model import LassoCV

In [41]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5)

In [43]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [44]:
lasso_cv_model.alpha_

0.49430709092258285

In [45]:
test_predictions = lasso_cv_model.predict(X_test)

In [46]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [47]:
MAE

12066.783260077276

In [48]:
MSE

316518869.605081

In [49]:
RMSE

17790.97719646341

In [51]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

# Elastic Net

Elastic Net combines the penalties of ridge regression and lasso in an attempt to get the best of both worlds!

In [54]:
from sklearn.linear_model import ElasticNetCV

In [55]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],tol=0.01)

In [56]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

In [57]:
elastic_model.l1_ratio_

1.0

In [58]:
test_predictions = elastic_model.predict(X_test)

In [59]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [60]:
MAE

5761524.973218833

In [61]:
MSE

82437947265656.42

In [62]:
RMSE

9079534.529129587

In [63]:
# Training Set Performance
# Training Set Performance
train_predictions = elastic_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.4307582990472368

In [64]:
elastic_model.coef_

array([ 3.78993643,  0.89232919,  0.28765395, -1.01843566,  2.15516144,
       -0.3567547 , -0.271502  ,  0.09741081,  0.        , -1.05563151,
        0.2362506 ,  0.07980911,  1.26170778,  0.01464706,  0.00462336,
       -0.39986069,  0.        ,  0.        , -0.05343757])